CREATE TABLE Item (
                      id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                      description varchar(100) not null,
                      price double precision
);
INSERT INTO Item (description, price) Values ('Asado Roll', 50.00);
INSERT INTO Item (description, price) Values ('Buko Pie', 100.00);
INSERT INTO Item (description, price) Values ('Cheese Bread', 20.00);
INSERT INTO Item (description, price) Values ('Egg Pie', 200.00);
INSERT INTO Item (description, price) Values ('Emapanada', 100.00);
INSERT INTO Item (description, price) Values ('Ensayamada', 10.00);
INSERT INTO Item (description, price) Values ('Hopia', 10.00);
INSERT INTO Item (description, price) Values ('Inipit', 5.00);
INSERT INTO Item (description, price) Values ('Mamon', 5.00);
INSERT INTO Item (description, price) Values ('Monay', 5.00);
